### ISSUE TITLE
Clientes

### ISSUE THREAD

**Issue by cuboalcub** [cuboalcub/front-Quijote#13]
![imagen](https://github.com/cuboalcub/front-Quijote/assets/115962355/17a03a05-e151-4b96-b3ce-8461343d3658)

- [ ] agregar tabla de clientes
- [ ] agregar botones 

mockups:
https://www.figma.com/file/hrx1iWM8nLlqfoatrjTN9N/Untitled?type=design&node-id=0-1&mode=design&t=ovMfwRnw2YKPU6tU-0

**Comment by ETE12** [comment]
acabao
