### ISSUE TITLE
Empleados

### ISSUE THREAD

**Issue by cuboalcub** [cuboalcub/front-Quijote#14]
![imagen](https://github.com/cuboalcub/front-Quijote/assets/115962355/4468234d-7344-4e35-8303-2e1a95c7f9d0)

- [x] agregar la tabla
- [x] agregar los botones
mockups:
https://www.figma.com/file/hrx1iWM8nLlqfoatrjTN9N/Untitled?type=design&node-id=0-1&mode=design&t=ovMfwRnw2YKPU6tU-0

**Comment by ETE12** [comment]
acabdo
