### ISSUE TITLE
Sucursales

### ISSUE THREAD

**Issue by cuboalcub** [cuboalcub/front-Quijote#15]
![imagen](https://github.com/cuboalcub/front-Quijote/assets/115962355/87a3e5c0-0bcb-45db-9941-6d30e0282110)

- [x] agregar tabla
- [x] agregar botones
mockups.
https://www.figma.com/file/hrx1iWM8nLlqfoatrjTN9N/Untitled?type=design&node-id=0-1&mode=design&t=z8LGa2jhuMnI318i-0

**Comment by ETE12** [comment]
acabao
