### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by cuboalcub** [cuboalcub/front-Quijote#2]
![imagen](https://github.com/cuboalcub/front-Quijote/assets/115962355/cd6350b7-1678-42e0-977a-4e5b60014afb)

- [x] subir el  logo de la libreria 
nota:
todo en app.components

front guia:https://www.figma.com/file/hrx1iWM8nLlqfoatrjTN9N/Untitled?type=design&node-id=0-1&mode=design&t=guilYgyBMXSMBAvq-0

**Comment by ETE12** [comment]
acabao
