### ISSUE TITLE
Inventario

### ISSUE THREAD

**Issue by cuboalcub** [cuboalcub/front-Quijote#3]
![imagen](https://github.com/cuboalcub/front-Quijote/assets/115962355/fe4018ab-f2cb-4767-85f6-4c7f0aab14f2)

- [x] Debe tener el titulo en la parte superior
- [x] Mostar la tabla de inventario
- [x] Tener un boton que agregue un libro
- [x] tener un boton que elimine un libro
- [x] en la misma tabla tenga un boton que sea la opcion de modifcar las caracteristicas del libro
front guia:https://www.figma.com/file/hrx1iWM8nLlqfoatrjTN9N/Untitled?type=design&node-id=0-1&mode=design&t=guilYgyBMXSMBAvq-0

**Comment by ETE12** [comment]
acabao
